In [5]:
import numpy as np
a=np.array([1,2,3])
print(a)
a.shape
dir(a)

[1 2 3]


['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '

In [7]:
b=[1,2,3,4,5,6]
arr= np.array(b, ndmin=2)
print(arr)

[[1 2 3 4 5 6]]


In [8]:
dt = np.dtype([('age',np.int8)])
a = np.array([(10,),(20,),(30,)], dtype=dt)
a['age']

array([10, 20, 30], dtype=int8)

In [9]:
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
b.ndim

2

In [13]:
arr=np.arange(10)
print(arr)
arr.itemsize
arr.flags

[0 1 2 3 4 5 6 7 8 9]


  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [15]:
arr.flags.writeable=False
arr[2]=1

ValueError: assignment destination is read-only

In [16]:
arr.flags.writeable

False

In [19]:
arr=np.empty((2,1), dtype=np.int8)

In [20]:
arr

array([[1],
       [1]], dtype=int8)

In [21]:
arr0= np.zeros([1,2])
arr0

array([[0., 0.]])

In [22]:
arr1=np.ones([2,4])
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
x = [1,2,3]
a = np.asarray(x)
a

array([1, 2, 3])

In [26]:
import numpy as np

x = [(1, 2, 3), (4, 5)]
a = np.asarray(x)
print(a)
print("Number of dimensions:", a.ndim)
print("Shape:", a.shape)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [28]:
#numpy.arange(start, stop, step, dtype)
x = np.arange(10,20,2)
x

array([10, 12, 14, 16, 18])

#numpy.linspace(start, stop, num, endpoint, retstep, dtype)
"""Array Creation
np.array(): Create an array from any object exposing the array interface.
np.zeros(): Create an array filled with zeros.
np.ones(): Create an array filled with ones.
np.empty(): Create an array with uninitialized values.
np.full(): Create an array filled with a specified value.
np.arange(): Create an array with regularly spaced values.
np.linspace(): Create an array with a specified number of evenly spaced values between two endpoints.
np.logspace(): Create an array with values spaced evenly on a log scale.
np.eye(): Create a 2D array with ones on the diagonal and zeros elsewhere (identity matrix).
np.diag(): Create a diagonal matrix or extract the diagonal of a matrix.
Array Manipulation
np.reshape(): Reshape an array without changing its data.
np.ravel(): Flatten a multi-dimensional array.
np.flatten(): Return a copy of the array collapsed into one dimension.
np.transpose(): Permute the dimensions of an array.
np.concatenate(): Join a sequence of arrays along an existing axis.
np.vstack(): Stack arrays vertically (row-wise).
np.hstack(): Stack arrays horizontally (column-wise).
np.split(): Split an array into multiple sub-arrays.
np.tile(): Construct an array by repeating a given array.
Mathematical Operations
np.add(): Add arguments element-wise.
np.subtract(): Subtract arguments element-wise.
np.multiply(): Multiply arguments element-wise.
np.divide(): Divide arguments element-wise.
np.power(): Raise values to the power of another array.
np.sqrt(): Compute the square root of an array element-wise.
np.exp(): Compute the exponential of all elements in the input array.
np.log(): Compute the natural logarithm of all elements in the input array.
np.sin(), np.cos(), np.tan(): Trigonometric functions.
Statistical Operations
np.mean(): Compute the arithmetic mean of elements.
np.median(): Compute the median of elements.
np.std(): Compute the standard deviation of elements.
np.var(): Compute the variance of elements.
np.min(): Find the minimum value in an array.
np.max(): Find the maximum value in an array.
np.sum(): Compute the sum of array elements.
np.prod(): Compute the product of array elements.
np.cumsum(): Compute the cumulative sum of array elements.
np.cumprod(): Compute the cumulative product of array elements.
Linear Algebra
np.dot(): Compute the dot product of two arrays.
np.matmul(): Matrix multiplication of two arrays.
np.linalg.inv(): Compute the (multiplicative) inverse of a matrix.
np.linalg.svd(): Singular Value Decomposition.
np.linalg.eig(): Compute the eigenvalues and right eigenvectors of a square array.
Miscellaneous
np.unique(): Find the unique elements of an array.
np.sort(): Return a sorted copy of an array.
np.argsort(): Return the indices that would sort an array.
np.where(): Return elements chosen from x or y depending on condition.
np.isnan(): Test element-wise for NaN and return a boolean array.
np.isfinite(): Test element-wise for finiteness (not infinity or NaN).
np.isnan(): Test element-wise for NaNs.
Random Sampling
np.random.rand(): Generate random numbers from a uniform distribution.
np.random.randn(): Generate random numbers from a normal distribution.
np.random.randint(): Generate random integers from a specified range.
np.random.choice(): Generate random samples from a given array."""